# Generated by Django 6.0.3 on 2026-09-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developments',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
